version: '2.1'
services:
  seleniumhub:
      image: selenium/standalone-chrome:3.4.0
      hostname: seleniumhub
      environment:
          # Required to avoid container startup hanging sometimes in
          # some environments
          JAVA_OPTS: -Djava.security.egd=file:/dev/./urandom
      ports:
          - "4444:4444"

  testservice:
      container_name: testservice
      build:
        context: .
      links:
        - seleniumhub
      env_file:
        - ${ENV}
      environment:
        - TEST_TAGS=${TEST_TAGS}