<ns4:walletBatchRequest
  xmlns:ns4="http://www.playtech.com/services/external/wallet"
  xmlns:ns5="http://www.playtech.com/services/common">
  <ns4:messageId>${messageID}</ns4:messageId>
  <ns4:replyToAddress>sunbets@automation_tabcorp_fictional.com.au</ns4:replyToAddress>
  <ns4:singleTransaction>true</ns4:singleTransaction>
  <ns4:playerIdentityByCasinoAndUsername>
    <ns5:casino>${gameProvider}</ns5:casino>
    <ns5:username>${username}</ns5:username>
  </ns4:playerIdentityByCasinoAndUsername>
  <ns4:authenticationByExternalToken>
    <ns5:systemId>${gameProvider}</ns5:systemId>
    <ns5:externalToken>${playTechAccessToken}</ns5:externalToken>
  </ns4:authenticationByExternalToken>
  <ns4:startGameSessionRequest>
    <ns4:messageId>${messageID}</ns4:messageId>
    <ns4:remoteSessionCode>1002-82</ns4:remoteSessionCode>
    <ns4:networkId>${gameProvider}</ns4:networkId>
    <ns4:remoteSessionStartDate>${timeStamp}</ns4:remoteSessionStartDate>
    <ns4:remoteSessionParameters>
    	<ns4:customData>
    		<ns4:gameType>${gameType}</ns4:gameType>
    	</ns4:customData>
    </ns4:remoteSessionParameters>
  </ns4:startGameSessionRequest>
  <ns4:gameMultiBalanceTransactionRequest>
    <ns4:messageId>${messageID}</ns4:messageId>
    <ns4:networkId>${gameProvider}</ns4:networkId>
    <ns4:transactionCode>${transactionCode}</ns4:transactionCode>
    <ns4:transactionDate>${timeStamp}</ns4:transactionDate>
    <ns4:actionType>ca_bet</ns4:actionType>
    <ns4:remoteSessionCode>1002-84</ns4:remoteSessionCode>
    <ns4:customData>
         <ns4:gameType>${gameType}</ns4:gameType>
      </ns4:customData>
    <ns4:balanceChanges>
      <ns4:balanceChange>
        <ns5:balanceType>external_real_balance</ns5:balanceType>
        <ns5:amount>
          <ns5:amount>${betAmount}</ns5:amount>
          <ns5:currencyCode>${currency}</ns5:currencyCode>
        </ns5:amount>
      </ns4:balanceChange>
    </ns4:balanceChanges>
  </ns4:gameMultiBalanceTransactionRequest>
</ns4:walletBatchRequest>
